FROM nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04

# Установим зависимости системы
RUN apt-get update && apt-get install -y \
    python3.10 \
    python3-pip \
    python3-venv \
    git \
    && rm -rf /var/lib/apt/lists/*

# Создадим виртуальное окружение
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Установим ключевые библиотеки для ML/DL (GPU)
RUN pip install --upgrade pip && \
    pip install \
    torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 \
    scikit-learn \
    pandas \
    numpy \
    matplotlib \
    seaborn \
    jupyter \
    opencv-python \
    transformers \
    && pip cache purge

# Установим рабочую директорию
WORKDIR /app

# Копируем содержимое репозитория в контейнер
COPY . /app

# Команда по умолчанию: запуск Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--allow-root", "--no-browser"]